format: table #json
exit-code: 1
vuln-type: 'os,library'
severity: 'CRITICAL,HIGH'
scanners: 'vuln,secret'
output: 'trivy-results.json' #<-reporte en json

ignore-unfixed: true # <- Oculta aquellas vulnerabilidades que todavía no tienen un parche

# secret:
#   config: config/trivy/secret.yaml