apiVersion: v1
kind: Pod
metadata:
  name: nginx-inseguro
spec:
  containers:
  - name: nginx
    image: nginx:latest
    securityContext:
      privileged: true   # <--- Mala práctica: contenedor con privilegios de root