name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-code:
    name: Build Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up a fake environment
        run: |
          echo "Setting up a fake environment for testing purposes."
          # Add any setup commands here

      - name: upload build
        uses: actions/upload-artifact@v4
        with:
          name: build-app
          path: app/blue/
          retention-days: 1

  image-scan-push:
    name: Scan and Push Docker Image
    runs-on: ubuntu-latest
    needs: [build-code]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: download build
        uses: actions/download-artifact@v4
        with:
          name: build-app
          path: dist/

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_ACCOUNT_NAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t codeparce/blue-green-app:blue ./dist
        shell: bash

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 'codeparce/blue-green-app:blue'
          trivy-config: trivy/config/docker.yml

      - name: Push Docker image``
        run: |
          docker push codeparce/blue-green-app:blue
        shell: bash

  check:
    name: Check for Vulnerabilities
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Trivy HTML template
      run: |
        wget https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl -O html.tpl

    - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@v0.36.0
      with:
        scan-type: 'fs'
        scan-ref: '.'
        trivy-config: trivy/config/file.yaml

    - name: upload report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: report-trivy
        path: trivy-report.html
        retention-days: 1